DROP TABLE RENTALS IF EXISTS;
DROP TABLE MOVIES IF EXISTS;
DROP TABLE USERS IF EXISTS;
DROP TABLE PRICECATEGORIES IF EXISTS;

CREATE TABLE USERS(
	USER_ID IDENTITY PRIMARY KEY,
	USER_EMAIL VARCHAR(255),
	USER_FIRSTNAME VARCHAR(255),
	USER_NAME VARCHAR(255)
);

CREATE TABLE PRICECATEGORIES(
	PRICECATEGORY_ID IDENTITY PRIMARY KEY,
	PRICECATEGORY_TYPE VARCHAR(255)
);

CREATE TABLE MOVIES(
	MOVIE_ID IDENTITY PRIMARY KEY,
	MOVIE_RELEASEDATE DATE,
	MOVIE_TITLE VARCHAR(255),
	MOVIE_RENTED BOOLEAN,
	PRICECATEGORY_FK BIGINT,
	CONSTRAINT FK_CATEGORY FOREIGN KEY(PRICECATEGORY_FK) REFERENCES PRICECATEGORIES(PRICECATEGORY_ID));

CREATE TABLE RENTALS(
	RENTAL_ID IDENTITY PRIMARY KEY,
	RENTAL_RENTALDATE DATE,
	RENTAL_RENTALDAYS INTEGER,
	USER_ID BIGINT,
	MOVIE_ID BIGINT,
	CONSTRAINT FK_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
	CONSTRAINT FK_MOVIE FOREIGN KEY(MOVIE_ID) REFERENCES MOVIES(MOVIE_ID)
);

