INSERT INTO PRICECATEGORIES (PRICECATEGORY_ID, PRICECATEGORY_TYPE) VALUES (1, 'Regular');
INSERT INTO PRICECATEGORIES (PRICECATEGORY_ID, PRICECATEGORY_TYPE) VALUES (2, 'Children');
INSERT INTO PRICECATEGORIES (PRICECATEGORY_ID, PRICECATEGORY_TYPE) VALUES (3, 'NewRelease');

INSERT INTO MOVIES (MOVIE_ID, MOVIE_RELEASEDATE, MOVIE_TITLE, MOVIE_RENTED, PRICECATEGORY_FK) VALUES (1, '2017-05-11', 'Marie Curie', true, 1);
INSERT INTO MOVIES (MOVIE_ID, MOVIE_RELEASEDATE, MOVIE_TITLE, MOVIE_RENTED, PRICECATEGORY_FK) VALUES (2, '2017-07-20', 'Curchill', true, 1);
INSERT INTO MOVIES (MOVIE_ID, MOVIE_RELEASEDATE, MOVIE_TITLE, MOVIE_RENTED, PRICECATEGORY_FK) VALUES (3, '2017-08-18', 'The Boss Baby', true, 2);
INSERT INTO MOVIES (MOVIE_ID, MOVIE_RELEASEDATE, MOVIE_TITLE, MOVIE_RENTED, PRICECATEGORY_FK) VALUES (4, '2017-08-31', 'Pirates of the Caribean: Salazar''s Revenge', false, 3);
INSERT INTO MOVIES (MOVIE_ID, MOVIE_RELEASEDATE, MOVIE_TITLE, MOVIE_RENTED, PRICECATEGORY_FK) VALUES (5, '2017-09-07', 'Die göttliche Ordnung', false, 3);
INSERT INTO MOVIES (MOVIE_ID, MOVIE_RELEASEDATE, MOVIE_TITLE, MOVIE_RENTED, PRICECATEGORY_FK) VALUES (6, '2018-05-25', 'Loving Vincent', false, 1);
INSERT INTO MOVIES (MOVIE_ID, MOVIE_RELEASEDATE, MOVIE_TITLE, MOVIE_RENTED, PRICECATEGORY_FK) VALUES (7, '2018-08-13', 'Fast & Furious 7', false, 3);
INSERT INTO MOVIES (MOVIE_ID, MOVIE_RELEASEDATE, MOVIE_TITLE, MOVIE_RENTED, PRICECATEGORY_FK) VALUES (8, '2018-10-01', 'Momo', false, 3);
INSERT INTO MOVIES (MOVIE_ID, MOVIE_RELEASEDATE, MOVIE_TITLE, MOVIE_RENTED, PRICECATEGORY_FK) VALUES (9, '2018-10-03', 'Swimming with Men', false, 3);
INSERT INTO MOVIES (MOVIE_ID, MOVIE_RELEASEDATE, MOVIE_TITLE, MOVIE_RENTED, PRICECATEGORY_FK) VALUES (10,'2018-10-22', 'Jurassic World', false, 3);

INSERT INTO USERS (USER_ID, USER_NAME, USER_FIRSTNAME, USER_EMAIL) VALUES (1, 'Keller', 'Marc', 'marc.keller@gmail.com');
INSERT INTO USERS (USER_ID, USER_NAME, USER_FIRSTNAME, USER_EMAIL) VALUES (2, 'Knecht', 'Werner', 'werner.knecht@gmail.com');
INSERT INTO USERS (USER_ID, USER_NAME, USER_FIRSTNAME, USER_EMAIL) VALUES (3, 'Meyer', 'Barbara', 'barbara.meyer@gmail.com');
INSERT INTO USERS (USER_ID, USER_NAME, USER_FIRSTNAME, USER_EMAIL) VALUES (4, 'Kummer', 'Adolf', 'adolf.kummer@gmail.com');

INSERT INTO RENTALS (RENTAL_ID, MOVIE_ID, USER_ID, RENTAL_RENTALDATE, RENTAL_RENTALDAYS) VALUES (1, 1, 1, '2018-09-23', 14);
INSERT INTO RENTALS (RENTAL_ID, MOVIE_ID, USER_ID, RENTAL_RENTALDATE, RENTAL_RENTALDAYS) VALUES (2, 2, 1, '2018-09-25', 14);
INSERT INTO RENTALS (RENTAL_ID, MOVIE_ID, USER_ID, RENTAL_RENTALDATE, RENTAL_RENTALDAYS) VALUES (3, 3, 3, '2018-09-27', 14);

